```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include = FALSE}
library(tidyverse)
library(sf)
library(tmap)

tmap_mode("view")

# Load and extract ----
epaWa <- st_read("../../static/files/gis/us_eco_l4_state_boundaries/us_eco_l4.shp") %>% 
  filter(STATE_NAME == "Washington") %>% 
  select(US_L4CODE, US_L4NAME, US_L3NAME)
```

# Visited Ecoregions

Map log detailing EPA Level IV ecoregions (dark lines), those visited (green fill), and trip details (markers).

```{r, out.width = '100%'}
visits <- read_csv("../../static/files/database/ecoregion-visits.csv")

epaWaVisited <- epaWa %>% 
  filter(US_L4CODE %in% visits$US_L4CODE) %>% 
  full_join(visits) %>% 
  select(-latitude, -longitude, -date, -activity)

visitPoints <- visits %>% 
  select(-US_L4CODE) %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

tm_shape(epaWa) +
  tm_polygons(alpha = 0) +
tm_shape(epaWaVisited) +
  tm_polygons(col = "forestgreen", alpha = 0.3) +
tm_shape(visitPoints) +
  tm_markers() +
tm_basemap(c("Esri.WorldTopoMap", "http://{s}.tiles.wmflabs.org/hikebike/{z}/{x}/{y}.png", "OpenStreetMap"))

```
